spring.application.name=ceppa_back


spring.datasource.url=jdbc:postgresql://localhost:5432/ceppa
spring.datasource.username=postgres
spring.datasource.password=postgrespassword

# Hibernate is disabled because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG
logging.level.org.flywaydb.core=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG