spring.application.name=ceppa_back
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/ceppa
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate is disabled because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG
logging.level.org.flywaydb.core=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG